--- 
github: 
  owner_name: "Ra√≠ B. Toffoletto"
  owner_url: "https://toffoletto.me"
  repository_name: Litteris
  zip_url: "https://github.com/raibtoffoletto/litteris/zipball/master"
show_downloads: false 
theme: jekyll-theme-architect
title: Litteris
